export default{
    png1:require("../assets/images/contemplative-reptile.jpg"),
    png2:require("../assets/images/u3.jpg"),
    png3:require("../assets/images/u5.jpg"),
    png4:require("../assets/images/u6.jpg"),
    png5:require("../assets/images/u7.jpg"),
    lsc:require("../assets/images/lsc.jpg"),
    fan:require("../assets/images/fan.jpg"),
    lb:require("../assets/images/41.jpg"),
    yonyou:require("../assets/images/mine/yonyou.png"),
    video:require("../assets/videos/movie.mp4"),
    video2:{uri:"http://124.129.157.208:8810/SD/zhishidian/grade_8_1/wuli_shu/01.mp4"},
    icon_biaoqian:require("../assets/images/icon_mainyy/icon_biaoqian.png"),
    icon_chengxu:require("../assets/images/icon_mainyy/icon_chengxu.png"),
    icon_diqiuyi:require("../assets/images/icon_mainyy/icon_diqiuyi.png"),
    icon_gengduo:require("../assets/images/icon_mainyy/icon_gengduo.png"),
    icon_jiaoyou:require("../assets/images/icon_mainyy/icon_jiaoyou.png"),
    icon_luying:require("../assets/images/icon_mainyy/icon_luying.png"),
    icon_pengyouquan:require("../assets/images/icon_mainyy/icon_pengyouquan.png"),
    icon_wenzhang:require("../assets/images/icon_mainyy/icon_wenzhang.png"),
    icon_secai:require("../assets/images/icon_mainyy/icon_secai.png"),
    icon_shuben:require("../assets/images/icon_mainyy/icon_shuben.png"),

    qitazonghe:require("../assets/images/icon_main/qitazonghe.png"),
    tongxunlu:require("../assets/images/icon_main/tongxunlu.png"),
    wanggou:require("../assets/images/icon_main/wanggou.png"),
    yinle:require("../assets/images/icon_main/yinle.png"),
    weixin:require("../assets/images/icon_main/weixin.png"),
    bofang:require("../assets/images/icon_main/bofang.png"),
    xuexiao:require("../assets/images/icon_main/xuexiao.png"),
    yonghu:require("../assets/images/icon_main/yonghu.png"),
    yonghushezhi:require("../assets/images/icon_main/yonghushezhi.png"),
    lvjia:require("../assets/images/icon_main/lvjia.png"),



}